import Head from 'next/head'
import {BiPlus} from 'react-icons/bi'
import Form from '@/components/form'
import Table from '@/components/table'
import { useState } from 'react'
import { useSelector,useDispatch } from 'react-redux'
import { toggleChangeAction, deleteAction } from '@/redux/reducer'
import { helperDeleteProduto, helperGetProdutos } from '@/lib/helper'
import { useQueryClient } from 'react-query'

export default function Home() {

  const visible = useSelector((state) => state.app.client.toggleForm)
  const deleteId = useSelector((state) => state.app.client.deleteId) //delete id vem do initial state na pasta reducer
  const queryclient = useQueryClient();
  const dispatch = useDispatch()

  const handler = () => {
    dispatch(toggleChangeAction())
  }

  const deletehandler = async() => {
    if(deleteId){
      await helperDeleteProduto(deleteId);
      await queryclient.prefetchQuery('produtos',helperGetProdutos)
      await dispatch(deleteAction(null))
    }
  }
  const cancelhandler = async () => {
    console.log("cancel")
    await dispatch(deleteAction(null))
  }
  //
  return (
    <section>
      <Head>
        <title>Crud App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center py-10'>
          Crud Produtos
        </h1>
        <div className='container mx-auto flex justify-between py-5 border-b-0'>
          <div className='left flex gap-3'>
            <button onClick={handler} className='flex bg-orange-500 text-md text-white px-4 py-2 border rounded-md hover:bg-green-500 hover:border-orange-500'>
              Adicionar novo produto <span className='px-1'><BiPlus size={24}></BiPlus></span>
            </button>
          </div>
          {deleteId ? DeleteComponent({deletehandler, cancelhandler}): <></>}
        </div>

        
        {visible ? <Form></Form>:<></>}
        
        <div className='container mx-auto'>
          <Table></Table>
        </div>

      </main>
    </section>
  )
}


function DeleteComponent({deletehandler, cancelhandler}){
  return(
    <div className='flex gap-5'>
      <button>Deseja deletar esse produto  ?</button>
      <button onClick={deletehandler} className='flex bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-red-500 hover:text-gray-500'>Deletar</button>
      <button onClick={cancelhandler}  className='flex bg-green-500 text-white px-4 py-2 border rounded-md hover:bg-green-500 hover:text-gray-500'>Cancelar</button>
    </div>
  )
}